### PR TITLE
Fix vector query planning and enforce file-format compatibility

### LINKED ISSUE #2881: [BUG] Vector index planning, pagination, ordering, and file-format compatibility gaps
**Version**

Current upstream `dev`, commit `a16129080e8e74409243cd4a5168709bf382fc94` (also the inspected workspace revision). Vector search was introduced in #2678.

This is a consolidated tracking issue for findings from code inspection. The scenarios below have **not been executed**; they should become regression tests. No claim of reproduced file corruption is made.

**Describe the bugs**

### 1. Ordinary index planning can select a vector index

`CollectionPage.InsertVectorIndex()` adds an `IndexType == 1` entry to the same `_indexes` dictionary as ordinary indexes. `QueryOptimization.ChooseIndex()` takes every collection index without filtering its type, then uses that list for predicates, grouping, ordering, and the preferred single-field projection fallback.

Consequently, a query that does not request vector search can select a vector index through the ordinary skip-list access path. That path does not implement traversal of the vector index.

Evidence: [collection registration](https://github.com/litedb-org/LiteDB/blob/a16129080e8e74409243cd4a5168709bf382fc94/LiteDB/Engine/Pages/CollectionPage.cs#L218), [ordinary planner](https://github.com/litedb-org/LiteDB/blob/a16129080e8e74409243cd4a5168709bf382fc94/LiteDB/Engine/Query/QueryOptimization.cs#L240).

Expected: ordinary index planning considers only supported ordinary index types. Other index types require their own access path. Cover predicates, `ORDER BY`, `GROUP BY`, and projection fallback, not just vector predicates.

### 2. Vector limit pushdown ignores offset and residual operations

`TrySelectVectorIndex()` passes `_query.Limit` directly into `VectorIndexQuery`, which passes it to `VectorIndexService.Search()`. Search truncates its results before the query pipeline applies remaining filters and pagination.

For example, `LIMIT 3 OFFSET 3` can receive only three candidates and then discard all three. A residual filter can similarly discard the first three candidates even though later vector matches satisfy the filter. Pushing a final result limit beneath a remaining sort or grouping operation also needs an explicit correctness check.

Evidence: [vector planning](https://github.com/litedb-org/LiteDB/blob/a16129080e8e74409243cd4a5168709bf382fc94/LiteDB/Engine/Query/QueryOptimization.cs#L310), [vector access path](https://github.com/litedb-org/LiteDB/blob/a16129080e8e74409243cd4a5168709bf382fc94/LiteDB/Engine/Query/IndexQuery/VectorIndexQuery.cs), [search truncation](https://github.com/litedb-org/LiteDB/blob/a16129080e8e74409243cd4a5168709bf382fc94/LiteDB/Engine/Services/VectorIndexService.cs#L94), [query pipeline](https://github.com/litedb-org/LiteDB/blob/a16129080e8e74409243cd4a5168709bf382fc94/LiteDB/Engine/Query/Pipeline/QueryPipe.cs).

Expected: only push limits through operations where it preserves query semantics. Accounting for offset alone does not solve residual filtering. Define any deliberately approximate candidate/filter behavior explicitly rather than silently changing ordinary query semantics.

### 3. Finding a vector sort expression removes the entire requested sort

`TrySelectVectorIndex()` searches all ordering segments for a vector expression, sets `_vectorOrderConsumed`, and `DefineOrderBy()` then sets the entire plan's `OrderBy` to null. It does not verify the requested direction, whether the vector expression is the primary ordering, or whether secondary ordering remains necessary.

For a cosine index, this can discard a requested descending distance order, a preceding non-vector sort key, or a secondary tie-breaker.

Evidence: [vector order selection](https://github.com/litedb-org/LiteDB/blob/a16129080e8e74409243cd4a5168709bf382fc94/LiteDB/Engine/Query/QueryOptimization.cs#L310), [sort removal](https://github.com/litedb-org/LiteDB/blob/a16129080e8e74409243cd4a5168709bf382fc94/LiteDB/Engine/Query/QueryOptimization.cs#L528).

Expected: remove sorting only when the access path satisfies the complete ordering contract; otherwise retain the required sort and avoid premature candidate truncation.

### 4. Vector storage additions have no distinguishing file-format gate

The implementation adds a vector BSON representation, `PageType.VectorIndex = 5`, and vector metadata in collection pages, while `HeaderPage.FILE_VERSION` remains `8`.

The header version therefore does not distinguish these files from files readable by older engines without vector support. This is a compatibility gap: an older engine can pass the header check without understanding all stored structures. Whether a particular operation subsequently fails or damages data needs cross-version testing.

Evidence: [header version](https://github.com/litedb-org/LiteDB/blob/a16129080e8e74409243cd4a5168709bf382fc94/LiteDB/Engine/Pages/HeaderPage.cs#L26), [page type](https://github.com/litedb-org/LiteDB/blob/a16129080e8e74409243cd4a5168709bf382fc94/LiteDB/Engine/Pages/BasePage.cs#L10), [collection metadata](https://github.com/litedb-org/LiteDB/blob/a16129080e8e74409243cd4a5168709bf382fc94/LiteDB/Engine/Pages/CollectionPage.cs#L71).

Expected: define and enforce the cross-version file compatibility boundary. Engines unable to preserve required structures must refuse unsafe access. A new metadata flag alone cannot protect against older binaries that ignore it.

**Regression scenarios to implement**

Create a small collection with a two-dimensional cosine vector index on `Embedding`, distinct distances to `@q`, and ordinary `Category` and `Rank` fields. Compare indexed execution to a reference result with explicitly defined distance semantics.

```sql
-- Ordinary projection must not select the vector index as a skip-list.
SELECT $.Embedding FROM docs

-- Pagination must not exhaust a prematurely truncated candidate stream.
SELECT $ FROM docs ORDER BY VECTOR_SIM($.Embedding, @q) LIMIT 3 OFFSET 3

-- Include matching documents beyond the first three unfiltered neighbors.
SELECT $ FROM docs WHERE $.Category = 'wanted'
ORDER BY VECTOR_SIM($.Embedding, @q) LIMIT 3

-- Preserve direction and the complete ordering tuple.
SELECT $ FROM docs ORDER BY VECTOR_SIM($.Embedding, @q) DESC
SELECT $ FROM docs ORDER BY $.Rank, VECTOR_SIM($.Embedding, @q)
SELECT $ FROM docs ORDER BY VECTOR_SIM($.Embedding, @q), $._id
```

These are proposed test shapes, not an executed reproduction. Add ordinary predicate/grouping cases, equal-distance tie cases, and cross-version opening/maintenance tests using disposable database copies.

**Completion checklist**

- [ ] Exclude vector indexes from every ordinary index-selection path.
- [ ] Make vector limit pushdown respect offset, residual filters, sorting, and grouping.
- [ ] Preserve sort direction, primary keys, and secondary ordering.
- [ ] Define and enforce vector file-format compatibility with older readers/writers.
- [ ] Add focused regressions for each finding and document any intentional ANN limitations.

**Additional context**

These issues concern the existing built-in vector implementation and should be addressed independently of the proposed plugin architecture in JKamsker/LiteDB#129. #2712 tracks a separate flaky vector test; #2724 tracks a previously reported corruption problem that is already closed.

### PR DESCRIPTION
**Pull request by JKamsker**
Fixes #2881.

Ordinary queries could select vector indexes through skip-list access. Vector queries could truncate candidates before filtering, pagination, or grouping and discard requested ordering. Vector structures also shared the released engine's v8 header.

**SQL behavior change:** SQL `VECTOR_SIM` never uses the vector index, including `ORDER BY VECTOR_SIM(...) LIMIT k`; SQL `EXPLAIN` never reports `VECTOR INDEX SEARCH`. ANN is available only through the explicit `TopKNear` and `WhereNear` APIs. This preserves scalar/null ordering semantics while keeping SQL on the ordinary planner and temporary-file sorter.

Ordinary planning now excludes vector indexes. SQL vector expressions use the normal planner, remain eligible for ordinary WHERE indexes, preserve undefined distances and null ordering, and sort through the existing temporary-file sorter. Explicit nearest-neighbor APIs retain ANN for simple bounded searches. Queries with residual operations stream projected documents, sort keys and addresses through the normal sorter, and reload by address without retaining the collection in memory. Repeated aggregate expressions reapply includes when replaying documents by address, so later aggregates retain expanded references without restoring a collection-wide document cache. Includes and WithScore preserve the selected index's metric, including Euclidean and dot product. Vector document and external-payload reads retain the engine's bounds. Scalar cosine predicates remain residual filters when combined with explicit vector APIs; they cannot replace the API's index, target, or metric threshold or truncate its candidates. Only the API-generated threshold predicate can be consumed by the selected vector index. WithScore copies that same predicate marker alongside WHERE terms, preserving metric thresholds and bounded ANN. Computed expressions such as COALESCE retain their canonical source when selecting a vector index. Expression identity preserves string-literal case while retaining case-insensitive field-name matching; different computed expressions cannot share index selection, API thresholds, or metric ordering.

The aggregate include-replay correction is a general engine fix. Ordinary queries using secondary indexes also retain expanded references across repeated FIRST/SUM aggregates. `AggregateIncludeReplay_Tests` covers sorted and unsorted execution, with and without filters on included fields, without vector data or indexes. The internal expression-identity helper now lives in `LiteDB.Engine`. Hand-built queries with an unparseable `VectorField` retain their previous ordinary-query fallback; vector API overloads still validate expressions at construction.

**Compatibility decision: preserve ordinary v8 files.** New ordinary files use v8, and existing v8 files remain readable/writable without migration, including read-only and Upgrade=true connections. The first BSON vector, vector index (including an empty index), or vector-index mutation flushes a v9 data header before vector pages can enter the WAL. Durable flushes propagate through the encryption and caller-stream wrappers to `FileStream.Flush(true)`. Promotion preserves the other persisted header fields and is monotonic across rollback, WAL replay, and checkpoint. Released LiteDB 5.0.21 refuses promoted files. Upgrade=true retains the existing v7 rebuild path, including an explicitly requested upgrade before opening read-only. Recovery fixtures now run unchanged. This implements the requested on-demand boundary; no bulk rebuild is required for ordinary v8 users.

A query accepts at most one WhereNear. Combining it with TopKNear requires the same expression and target; unsupported combinations throw before mutating the query. This rule is documented in the API XML comments.

Durable flushes through encrypted/caller-stream wrappers affect promotion, checkpoint, recovery-marker writes, and stream initialization. Checkpoint latency now includes a real disk sync on those paths. WAL commit still uses parameterless Flush; the review's cited DiskService line 288 belongs to MarkAsInvalidState, not commit. A production-build probe of 1,000 ordinary transactions observed zero durable flushes during commits and one data-file durable flush each for checkpoint and promotion, in both plain and encrypted modes. The reproducible probe and local timing samples are in tools/VectorFlushProbe and docs/vector-query-compatibility.md.

Exact vector queries still require a complete distance scan and can use temporary disk space for sorting. ANN remains approximate. A rolled-back first vector write can conservatively leave the file on v9. Development builds that previously wrote vectors under v8 cannot be retroactively protected from older engines. See `docs/vector-query-compatibility.md` for details.

The original reproduction remains in the distinct test-only commit `df989667` (22 failures and 9 passing regressions), followed by implementation commit `88411dc8`. Review follow-ups include `1e6a7283` for streaming query execution and `072175ff` for ordinary v8 compatibility. Latest dev runtime/mapper changes are merged in `6dae4b8d`; `65010044` permits shared inspection of the open data file in Windows promotion tests.

Validation:

- Release solution build with TestingEnabled=true: passed.
- [CI on `413e7926`](https://github.com/litedb-org/LiteDB/actions/runs/34768450265): passed; all 46 PR checks are green.
- Full .NET 8 and .NET 10 suites: 801 passed, 7 existing skips each. ReproRunner tests: 18 passed.
- Review regression tests initially reproduced four query execution failures and eleven compatibility failures. The latest distinct test-only commit `2e54b7bc` adds a baseline with 12 failures and 3 passing regressions for scalar/API predicate separation, underlying durable flushes, and read-only v7 upgrades. All pass after implementation commit `d823c546`, which also avoids the promotion lock for already-promoted files and keeps header loads from writing into readable buffers.
- Coverage includes undefined vectors, filter-index selection, projection and sort spilling, metric ordering with includes/scores, parser arity, vector promotion before commit, rollback, stale WAL headers, shared/encrypted connections, concurrent writes, and injected promotion write/flush failures, underlying file fsync failures, v7 read-only upgrades, and header savepoint version preservation.
- Separate processes using released LiteDB 5.0.21 and the current engine exchange ordinary files in both directions, then verify rejection without modification after a vector value or empty vector index promotes them. Plain and encrypted cases, vector rebuild, and reopening promoted files pass. Included in Linux CI.
- The latest test-only commit `c4aa9693` reproduces 18 failures covering scored/plain parity, projected snapshots, computed expressions, bounded ANN, and unsupported API combinations. All pass after implementation commit `8b51f487`.
- A four-reviewer follow-up reproduced an included-document aggregate replay regression in test-only commit `ae893866` (four failures), fixed in `2e27aa9e`. TopKNear API remarks and query-validation documentation nits are corrected.
- A second four-reviewer round reproduced case-sensitive computed-expression mismatches in test-only commit `4ac6a8f8` (eight failures and one passing control), fixed in `1e8b83db`. Coverage includes index selection, API composition, scalar ordering, and field-name casing.
- A third four-reviewer round reproduced quoted-field casing regressions in test-only commit `ab48db18` (eight failures), fixed in `b2d20a40`. Quoted field identifiers remain case-insensitive in direct/computed expressions and composed queries, while string values remain case-sensitive.
- A fourth independent four-reviewer round found no issues above nits. Its remaining SQL documentation wording nit is corrected in `4c150042`. All reviewers used `gpt-6-astra` at high reasoning effort without inherited conversation context.
- External review follow-up: test-only commit `d6884f25` adds four passing ordinary aggregate replay cases and two failing manual-query fallback cases; implementation `6b8e2d3a` resolves the latter and moves expression identity into the engine namespace. The ordinary-query fixture does not assume ordering among equal secondary-index keys. Four fresh reviewers found no functional issues; their one coverage nit is addressed in `413e7926` with a selective included-field predicate that verifies replay retains the filtered membership.
- C# size and whitespace checks pass. All addressed review threads are resolved.

The review-body reopen finding is covered by `d83f5b99`: the reopened database must select `embedding_idx` with `VECTOR INDEX SEARCH` and return the expected TopKNear result.

### CODE REVIEW

File: LiteDB/Engine/Query/IndexQuery/VectorIndexQuery.cs [hunk 1]
```diff
@@ -69,6 +72,33 @@ public override IEnumerable<IndexNode> Run(CollectionPage col, IndexService inde
...
+        private IEnumerable<(BsonDocument Document, double Distance)> Scan(IndexService indexer)
+        {
+            var data = new DataService(_snapshot, uint.MaxValue);
+            var lookup = new DatafileLookup(data, false, null);
+            foreach (var node in indexer.FindAll(_snapshot.CollectionPage.PK, Query.Ascending))
+            {
+                var document = lookup.Load(node);
+                var value = _index.BsonExpr.ExecuteScalar(document, _collation);
+                _snapshot.Safepoint();
+                if (!VectorIndexService.TryExtractVector(value, _metadata.Dimensions, out var vector)) continue;
```
[the remark this answers is not in the document]
Comment (JKamsker) [reply LiteDB/Engine/Query/IndexQuery/VectorIndexQuery.cs]: Fixed in a2775548. SQL vector evaluation now retains every document and uses the scalar VECTOR_SIM result, including BsonValue.Null, as its sort key. SQL predicates stay in the normal pipeline, and bounded SQL sorts also use complete evaluation so undefined rows cannot disappear through ANN truncation. Added 56 parameterized regressions covering missing, null, invalid, mismatched, zero, and non-finite vectors across sorting, pagination, filtering, and grouping; both function and infix syntax match unindexed execution. The merged metric-score/secondary-sort tests also pass.

File: LiteDB/Engine/Query/IndexQuery/VectorIndexQuery.cs [hunk 2]
```diff
@@ -69,6 +72,33 @@ public override IEnumerable<IndexNode> Run(CollectionPage col, IndexService inde
             }
         }
 
+        private IEnumerable<(BsonDocument Document, double Distance)> Scan(IndexService indexer)
+        {
+            var data = new DataService(_snapshot, uint.MaxValue);
+            var lookup = new DatafileLookup(data, false, null);
```
[the remark this answers is not in the document]
Comment (JKamsker) [reply LiteDB/Engine/Query/IndexQuery/VectorIndexQuery.cs]: Fixed in a2775548. Snapshot exposes the engine maximum item count, and complete vector scans, ANN document reads, and external-vector data reads now pass that bound to DataService. Added valid multi-page document/external-vector coverage for ANN, filtered scored queries, and SQL sorting, before and after checkpoint. Full .NET 8 validation: 716 passed, 7 existing skips; Release solution build and cross-version checks passed.

**Comment by JKamsker** [comment]
@codex review thoroughly

File: LiteDB/Engine/Disk/DiskService.FileVersion.cs [hunk 3]
```diff
@@ -0,0 +1,54 @@
...
+                if (header[HeaderPage.P_FILE_VERSION] != HeaderPage.FILE_VERSION &&
+                    header[HeaderPage.P_FILE_VERSION] != HeaderPage.VECTOR_FILE_VERSION)
+                {
+                    throw LiteException.UnsupportedFileVersion(header[HeaderPage.P_FILE_VERSION]);
+                }
+                header[HeaderPage.P_FILE_VERSION] = HeaderPage.VECTOR_FILE_VERSION;
+                stream.Position = 0;
+                // A full page also works with encrypted streams; all other header fields are preserved.
+                stream.Write(header, 0, header.Length);
+                stream.FlushToDisk();
```
[the remark this answers is not in the document]
Comment (JKamsker) [reply LiteDB/Engine/Disk/DiskService.FileVersion.cs:41]: Fixed in d823c546. Durable flush requests now traverse AesStream and ConcurrentStream to the underlying FileStream.Flush(true), without changing ordinary parameterless Flush behavior. The test-only commit 2e54b7bc reproduces the missing durable flush through both wrappers. Added underlying-file flush tracking and failure injection for plain/encrypted promotion, verifying that vector pages cannot reach the WAL before the durable flush and that failed promotion leaves only the original document on reopen. Release build, full .NET 8/.NET 10 suites (756 passed, 7 existing skips each), and released-engine compatibility checks pass.

File: LiteDB/Engine/Engine/Upgrade.cs [hunk 4]
```diff
@@ -20,25 +20,19 @@ private void TryUpgrade()
         {
             var filename = _settings.Filename;
 
-            // if file not exists, just exit
-            if (!File.Exists(filename)) return;
+            // Only v7 requires a rebuild. Ordinary v8 files remain compatible.
+            if (_settings.ReadOnly || !File.Exists(filename)) return;
```
[the remark this answers is not in the document]
Comment (JKamsker) [reply LiteDB/Engine/Engine/Upgrade.cs]: Fixed in d823c546. TryUpgrade again performs an explicitly requested v7 rebuild before applying read-only access. Regression tests in the separate test-only commit 2e54b7bc use the existing plain and encrypted v4/v7 fixtures; they verify successful upgrade, preserved backup bytes, readable contents, rejected writes, and reopening read-only. Ordinary v8 files still open without rebuilding. Full .NET 8/.NET 10 suites and released-engine compatibility checks pass.

**Comment by JKamsker** [comment]
Addressed the CodeRabbit review-body comment about reopen coverage in d83f5b99. The rebuilt database now verifies `embedding_idx` and `VECTOR INDEX SEARCH` in the reopened query plan, then runs TopKNear and checks the result, alongside the existing persisted BSON vector assertion. The focused format suite passes (4 tests).

**Comment by JKamsker** [comment]
Addressed the CodeRabbit review-body finding in 8b51f487: WithScore now copies the exact VectorFilter marker alongside WHERE terms. Tests cover non-collinear Euclidean and negative dot-product thresholds, projection and repeatable snapshots, and verify bounded scored ANN does not spill a full collection sort. The same commit preserves computed vector expression sources and rejects repeated/mismatched API combinations before changing the query. Separate test-only commit c4aa9693 had 18 failing cases. Full .NET 8 and .NET 10 suites now each pass 774 tests with seven existing skips; cross-version checks pass.
