### ISSUE TITLE
[BUG] Vector index planning, pagination, ordering, and file-format compatibility gaps

### ISSUE THREAD

**Issue by JKamsker** [litedb-org/LiteDB#2881]
**Version**

Current upstream `dev`, commit `a16129080e8e74409243cd4a5168709bf382fc94` (also the inspected workspace revision). Vector search was introduced in #2678.

This is a consolidated tracking issue for findings from code inspection. The scenarios below have **not been executed**; they should become regression tests. No claim of reproduced file corruption is made.

**Describe the bugs**

### 1. Ordinary index planning can select a vector index

`CollectionPage.InsertVectorIndex()` adds an `IndexType == 1` entry to the same `_indexes` dictionary as ordinary indexes. `QueryOptimization.ChooseIndex()` takes every collection index without filtering its type, then uses that list for predicates, grouping, ordering, and the preferred single-field projection fallback.

Consequently, a query that does not request vector search can select a vector index through the ordinary skip-list access path. That path does not implement traversal of the vector index.

Evidence: [collection registration](https://github.com/litedb-org/LiteDB/blob/a16129080e8e74409243cd4a5168709bf382fc94/LiteDB/Engine/Pages/CollectionPage.cs#L218), [ordinary planner](https://github.com/litedb-org/LiteDB/blob/a16129080e8e74409243cd4a5168709bf382fc94/LiteDB/Engine/Query/QueryOptimization.cs#L240).

Expected: ordinary index planning considers only supported ordinary index types. Other index types require their own access path. Cover predicates, `ORDER BY`, `GROUP BY`, and projection fallback, not just vector predicates.

### 2. Vector limit pushdown ignores offset and residual operations

`TrySelectVectorIndex()` passes `_query.Limit` directly into `VectorIndexQuery`, which passes it to `VectorIndexService.Search()`. Search truncates its results before the query pipeline applies remaining filters and pagination.

For example, `LIMIT 3 OFFSET 3` can receive only three candidates and then discard all three. A residual filter can similarly discard the first three candidates even though later vector matches satisfy the filter. Pushing a final result limit beneath a remaining sort or grouping operation also needs an explicit correctness check.

Evidence: [vector planning](https://github.com/litedb-org/LiteDB/blob/a16129080e8e74409243cd4a5168709bf382fc94/LiteDB/Engine/Query/QueryOptimization.cs#L310), [vector access path](https://github.com/litedb-org/LiteDB/blob/a16129080e8e74409243cd4a5168709bf382fc94/LiteDB/Engine/Query/IndexQuery/VectorIndexQuery.cs), [search truncation](https://github.com/litedb-org/LiteDB/blob/a16129080e8e74409243cd4a5168709bf382fc94/LiteDB/Engine/Services/VectorIndexService.cs#L94), [query pipeline](https://github.com/litedb-org/LiteDB/blob/a16129080e8e74409243cd4a5168709bf382fc94/LiteDB/Engine/Query/Pipeline/QueryPipe.cs).

Expected: only push limits through operations where it preserves query semantics. Accounting for offset alone does not solve residual filtering. Define any deliberately approximate candidate/filter behavior explicitly rather than silently changing ordinary query semantics.

### 3. Finding a vector sort expression removes the entire requested sort

`TrySelectVectorIndex()` searches all ordering segments for a vector expression, sets `_vectorOrderConsumed`, and `DefineOrderBy()` then sets the entire plan's `OrderBy` to null. It does not verify the requested direction, whether the vector expression is the primary ordering, or whether secondary ordering remains necessary.

For a cosine index, this can discard a requested descending distance order, a preceding non-vector sort key, or a secondary tie-breaker.

Evidence: [vector order selection](https://github.com/litedb-org/LiteDB/blob/a16129080e8e74409243cd4a5168709bf382fc94/LiteDB/Engine/Query/QueryOptimization.cs#L310), [sort removal](https://github.com/litedb-org/LiteDB/blob/a16129080e8e74409243cd4a5168709bf382fc94/LiteDB/Engine/Query/QueryOptimization.cs#L528).

Expected: remove sorting only when the access path satisfies the complete ordering contract; otherwise retain the required sort and avoid premature candidate truncation.

### 4. Vector storage additions have no distinguishing file-format gate

The implementation adds a vector BSON representation, `PageType.VectorIndex = 5`, and vector metadata in collection pages, while `HeaderPage.FILE_VERSION` remains `8`.

The header version therefore does not distinguish these files from files readable by older engines without vector support. This is a compatibility gap: an older engine can pass the header check without understanding all stored structures. Whether a particular operation subsequently fails or damages data needs cross-version testing.

Evidence: [header version](https://github.com/litedb-org/LiteDB/blob/a16129080e8e74409243cd4a5168709bf382fc94/LiteDB/Engine/Pages/HeaderPage.cs#L26), [page type](https://github.com/litedb-org/LiteDB/blob/a16129080e8e74409243cd4a5168709bf382fc94/LiteDB/Engine/Pages/BasePage.cs#L10), [collection metadata](https://github.com/litedb-org/LiteDB/blob/a16129080e8e74409243cd4a5168709bf382fc94/LiteDB/Engine/Pages/CollectionPage.cs#L71).

Expected: define and enforce the cross-version file compatibility boundary. Engines unable to preserve required structures must refuse unsafe access. A new metadata flag alone cannot protect against older binaries that ignore it.

**Regression scenarios to implement**

Create a small collection with a two-dimensional cosine vector index on `Embedding`, distinct distances to `@q`, and ordinary `Category` and `Rank` fields. Compare indexed execution to a reference result with explicitly defined distance semantics.

```sql
-- Ordinary projection must not select the vector index as a skip-list.
SELECT $.Embedding FROM docs

-- Pagination must not exhaust a prematurely truncated candidate stream.
SELECT $ FROM docs ORDER BY VECTOR_SIM($.Embedding, @q) LIMIT 3 OFFSET 3

-- Include matching documents beyond the first three unfiltered neighbors.
SELECT $ FROM docs WHERE $.Category = 'wanted'
ORDER BY VECTOR_SIM($.Embedding, @q) LIMIT 3

-- Preserve direction and the complete ordering tuple.
SELECT $ FROM docs ORDER BY VECTOR_SIM($.Embedding, @q) DESC
SELECT $ FROM docs ORDER BY $.Rank, VECTOR_SIM($.Embedding, @q)
SELECT $ FROM docs ORDER BY VECTOR_SIM($.Embedding, @q), $._id
```

These are proposed test shapes, not an executed reproduction. Add ordinary predicate/grouping cases, equal-distance tie cases, and cross-version opening/maintenance tests using disposable database copies.

**Completion checklist**

- [ ] Exclude vector indexes from every ordinary index-selection path.
- [ ] Make vector limit pushdown respect offset, residual filters, sorting, and grouping.
- [ ] Preserve sort direction, primary keys, and secondary ordering.
- [ ] Define and enforce vector file-format compatibility with older readers/writers.
- [ ] Add focused regressions for each finding and document any intentional ANN limitations.

**Additional context**

These issues concern the existing built-in vector implementation and should be addressed independently of the proposed plugin architecture in JKamsker/LiteDB#129. #2712 tracks a separate flaky vector test; #2724 tracks a previously reported corruption problem that is already closed.
